---
- name: Configure user on Ubuntu
  hosts: jonathan-ec2
  become: yes
  remote_user: ubuntu
  
  tasks:
    - name: Create dev user with admin priviliges
      user:
        name: "{{ dev_user }}"
        createhome: yes
        shell: /bin/bash

    - name: Add dev user's public key
      authorized_key:
        user: "{{ dev_user }}"
        key: "{{ lookup('vars', dev_user)['ssh_pubkey'] }}"
        state: present

    - name: Add dev user to the admin sudo group
      user:
        name: "{{ dev_user }}"
        groups: admin
        append: yes
    
    #https://stackoverflow.com/questions/46720411/is-it-safe-to-edit-etc-sudoers-with-the-ansible-lineinfile-module
    - name: Configure sudo settings for dev user
      lineinfile:
        dest: /etc/sudoers
        line: "{{ dev_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'

    - name: Reload sudo configuration
      command: visudo -c
