---

- hosts: all
  gather_facts: false
  remote_user: ubuntu
  vars:
    dev_user: 'francis'
  tasks:
    - name: Ping task
      ping:

    - name: Debug task 1
      debug: 
        msg="{{ lookup('vars',dev_user)['ssh_pubkey'] }}"