---

- hosts: all
  gather_facts: false
  remote_user: ubuntu
  vars:
    user: francis
  tasks:
    - name: Ping task
      ping:

    - name: Debug task
      debug:
        msg: "User {{ dev_users['{{ user }}']['ssh_pubkey'] }}"