---

- hosts: all
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Ping task
      ping:

    - name: Debug task
      debug:
        msg: "Francis {{ dev_users['francis']['ssh_pubkey'] }}"